# development configuration
version: '3.8'
services:

  solar-system-info-bot:
    build:
      context: ..
      dockerfile: ./grpc-telegram-bot/bot/Dockerfile

  solar-system-info-server:
    build:
      context: ..
      dockerfile: ./grpc-telegram-bot/server/Dockerfile

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
