[package]
name = "solar-system-info-rpc"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2018"

[dependencies]
tonic = "0.6.2"
prost = "0.9.0"
prost-types = "0.9.0"

[build-dependencies]
tonic-build = "0.6.2"
