[package]
name = "mongodb-redis"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2018"

[dependencies]
mongodb = "2.0.0-beta.3"
redis = { version = "0.21.0", features = ["tokio-comp", "connection-manager"] }
actix-web = "4.0.0-beta.8"
tokio = "1.10.0"
tokio-stream = "0.1.7"
chrono = { version = "0.4.19", features = ["serde"] }
serde = "1.0.127"
serde_json = "1.0.66"
dotenv = "0.15.0"
derive_more = "0.99.16"
log = "0.4.14"
env_logger = "0.9.0"
rust-embed = "6.0.0"
mime = "0.3.16"
